import Head from 'next/head'
import React from 'react'
import TopAd from '../../src/Components/HomeComponents/TopAd/TopAd'
import Navbar from '../../src/Components/Navbar/Navbar'
import FilterSection from '../../src/Components/ProductsComponents/Filter/FilterSection'
import ProductSection from '../../src/Components/ProductsComponents/ProductSection/ProductSection'
import { Box } from '@mui/material'

const Products = () => {
  return (
    <>
    <Head>
      <title>FAT SALE</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />

    </Head>
    <TopAd/>
    <Navbar/>
    <Box className='flexed' sx={{flexWrap:'wrap',mx:'1em',mt:'2em',alignItems:'flex-start',flexDirection:'row'}}>
    <FilterSection/>
    <ProductSection/>
    </Box>
  </>
  )
}

export default Products