import Head from 'next/head'
import React from 'react'
import TopAd from '../src/Components/HomeComponents/TopAd/TopAd'
import Navbar from '../src/Components/Navbar/Navbar'
import CategoryMenu from '../src/Components/HomeComponents/CategoryMenu/CategoryMenu'
import { Box } from '@mui/material'

const cart = () => {
  return (
    <>
        <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopAd/>
      <Navbar/>
      <CategoryMenu/>

      <main>
        <Box sx={{}}>

        </Box>
      </main>
    </>
  )
}

export default cart