import Head from 'next/head'
import Navbar from '../src/Components/Navbar/Navbar'
import TopAd from '../src/Components/TopAd/TopAd'
import CategoryMenu from '../src/Components/CategoryMenu/CategoryMenu'
import { Box, IconButton } from '@mui/material';
import MainCarousel from '../src/Components/MainCarousel/MainCarousel';
import WhatsApp from '../src/Components/SocialLinks/WhatsApp';
import ProductCollection from '../src/Components/ProductCollection/ProductCollection';

export default function Home() {
  return (
    <>
      <Head>
        <title>FAT SALE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <TopAd/>
      <Navbar/>
      <CategoryMenu/>
      <main>
      <MainCarousel/>
      <WhatsApp/>
      <ProductCollection title='Christmas Sale'/>      
      </main>
    </>
  )
}
